matrix:
  include:
    - language: node_js
      name: "Server"
      node_js: 10
      before_script:
        - cd server
        - npm run setup
        - npm run build
      script:
        - npm run test

    - language: node_js
      name: "Web client"
      node_js: 10
      before_script:
        - cd web_client
        - npm run setup
        - npm run build
      script:
        - npm run test