version: '3'
services:
  client_web:
    container_name: 'area_web_client'
    build:
      context: ./web_client
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      - PORT=8081
    volumes:
      - 'apk-volume:/var/lib/apk/'
    depends_on:
      - client_mobile
  client_mobile:
    container_name: 'area_mobile_client'
    volumes:
      - 'apk-volume:/home/cirrus/apk'
    build:
      context: ./mobile_client
      dockerfile: Dockerfile
  db:
    container_name: 'area_db'

volumes:
  apk-volume: