version: '3'
services:
  client_web:
    container_name: 'area_web_client'
    build:
      context: ./web_client
      dockerfile: Dockerfile
    ports:
      - '8081:80'
    volumes:
      - 'apk-volume:/var/lib/apk/'
    depends_on:
      - client_mobile
      - server
    restart: always
    environment:
      REACT_APP_API_URL: http://localhost:8080 #In the context of the client browser

  client_mobile:
    container_name: 'area_mobile_client'
    volumes:
      - 'apk-volume:/home/cirrus/apk'
    build:
      context: ./mobile_client
      dockerfile: Dockerfile

  server:
      image: area_server:v1
      build:
          context: server/
      depends_on:
        - db
      environment:
          MONGODB_URI: mongodb://area:area@db:27017
          DB_NAME: area
          PORT: 8080
      networks:
        - server_net
      ports:
        - "8080:8080"
      restart: always

  db:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: area
        MONGO_INITDB_ROOT_PASSWORD: area
        MONGO_INITDB_DATABASE: area
      volumes:
        - "dbdata:/data/db"
      networks:
        - server_net


networks:
  server_net:

volumes:
  apk-volume:
  dbdata: